services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: rapidlog
    restart: always
    ports:
      - "1509:1508"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${RAPIDLOG_DB_USER}
      POSTGRES_PASSWORD: ${RAPIDLOG_DB_PASSWORD}
      POSTGRES_DB: ${RAPIDLOG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${RAPIDLOG_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
