services:
  gate:
    build:
      context: .
      dockerfile: Dockerfile
      target: gate
    container_name: gate
    image: rapidlog-gate
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
      - identity

  identity:
    build:
      context: .
      dockerfile: Dockerfile
      target: identity
    container_name: identity
    image: rapidlog-identity
    restart: always
    ports:
      - '50051:50051'
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rapidlog
      POSTGRES_PASSWORD: rapidlog
      POSTGRES_DB: rapidlog
    configs:
      - source: init-identity-db
        target: /docker-entrypoint-initdb.d/init-identity-db.sql
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'rapidlog']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  postgres_data:

configs:
  init-identity-db:
    content: |
      CREATE DATABASE identity;
