services:
  gate:
    build:
      context: .
      dockerfile: Dockerfile
      target: gate
    container_name: gate
    restart: always
    ports:
      - '9000:8080'
    depends_on:
      - identity

  identity:
    build:
      context: .
      dockerfile: Dockerfile
      target: identity
    container_name: identity
    restart: always
    ports:
      - '50051:50051'
