// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alexnesterov/rapidlog-api/internal/domain/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBulletRepository creates a new instance of MockBulletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBulletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBulletRepository {
	mock := &MockBulletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBulletRepository is an autogenerated mock type for the BulletRepository type
type MockBulletRepository struct {
	mock.Mock
}

type MockBulletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBulletRepository) EXPECT() *MockBulletRepository_Expecter {
	return &MockBulletRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) Create(bullet *entity.Bullet) error {
	ret := _mock.Called(bullet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Bullet) error); ok {
		r0 = returnFunc(bullet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBulletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBulletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - bullet *entity.Bullet
func (_e *MockBulletRepository_Expecter) Create(bullet any) *MockBulletRepository_Create_Call {
	return &MockBulletRepository_Create_Call{Call: _e.mock.On("Create", bullet)}
}

func (_c *MockBulletRepository_Create_Call) Run(run func(bullet *entity.Bullet)) *MockBulletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Bullet
		if args[0] != nil {
			arg0 = args[0].(*entity.Bullet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBulletRepository_Create_Call) Return(err error) *MockBulletRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBulletRepository_Create_Call) RunAndReturn(run func(bullet *entity.Bullet) error) *MockBulletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) Get(id uuid.UUID) (*entity.Bullet, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entity.Bullet, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entity.Bullet); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBulletRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBulletRepository_Expecter) Get(id any) *MockBulletRepository_Get_Call {
	return &MockBulletRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockBulletRepository_Get_Call) Run(run func(id uuid.UUID)) *MockBulletRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBulletRepository_Get_Call) Return(bullet *entity.Bullet, err error) *MockBulletRepository_Get_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletRepository_Get_Call) RunAndReturn(run func(id uuid.UUID) (*entity.Bullet, error)) *MockBulletRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) List() ([]*entity.Bullet, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Bullet, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Bullet); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBulletRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockBulletRepository_Expecter) List() *MockBulletRepository_List_Call {
	return &MockBulletRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockBulletRepository_List_Call) Run(run func()) *MockBulletRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBulletRepository_List_Call) Return(bullets []*entity.Bullet, err error) *MockBulletRepository_List_Call {
	_c.Call.Return(bullets, err)
	return _c
}

func (_c *MockBulletRepository_List_Call) RunAndReturn(run func() ([]*entity.Bullet, error)) *MockBulletRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
