// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alexnesterov/rapidlog-api/internal/domain/entity"
	"github.com/alexnesterov/rapidlog-api/internal/domain/port"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBulletService creates a new instance of MockBulletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBulletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBulletService {
	mock := &MockBulletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBulletService is an autogenerated mock type for the BulletService type
type MockBulletService struct {
	mock.Mock
}

type MockBulletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBulletService) EXPECT() *MockBulletService_Expecter {
	return &MockBulletService_Expecter{mock: &_m.Mock}
}

// CancelBullet provides a mock function for the type MockBulletService
func (_mock *MockBulletService) CancelBullet(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBullet")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Bullet, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Bullet); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_CancelBullet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBullet'
type MockBulletService_CancelBullet_Call struct {
	*mock.Call
}

// CancelBullet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockBulletService_Expecter) CancelBullet(ctx any, id any, userID any) *MockBulletService_CancelBullet_Call {
	return &MockBulletService_CancelBullet_Call{Call: _e.mock.On("CancelBullet", ctx, id, userID)}
}

func (_c *MockBulletService_CancelBullet_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockBulletService_CancelBullet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBulletService_CancelBullet_Call) Return(bullet *entity.Bullet, err error) *MockBulletService_CancelBullet_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletService_CancelBullet_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error)) *MockBulletService_CancelBullet_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteBullet provides a mock function for the type MockBulletService
func (_mock *MockBulletService) CompleteBullet(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteBullet")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Bullet, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Bullet); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_CompleteBullet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteBullet'
type MockBulletService_CompleteBullet_Call struct {
	*mock.Call
}

// CompleteBullet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockBulletService_Expecter) CompleteBullet(ctx any, id any, userID any) *MockBulletService_CompleteBullet_Call {
	return &MockBulletService_CompleteBullet_Call{Call: _e.mock.On("CompleteBullet", ctx, id, userID)}
}

func (_c *MockBulletService_CompleteBullet_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockBulletService_CompleteBullet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBulletService_CompleteBullet_Call) Return(bullet *entity.Bullet, err error) *MockBulletService_CompleteBullet_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletService_CompleteBullet_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error)) *MockBulletService_CompleteBullet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBullet provides a mock function for the type MockBulletService
func (_mock *MockBulletService) CreateBullet(ctx context.Context, input port.CreateBulletInput) (*entity.Bullet, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBullet")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.CreateBulletInput) (*entity.Bullet, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.CreateBulletInput) *entity.Bullet); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.CreateBulletInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_CreateBullet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBullet'
type MockBulletService_CreateBullet_Call struct {
	*mock.Call
}

// CreateBullet is a helper method to define mock.On call
//   - ctx context.Context
//   - input port.CreateBulletInput
func (_e *MockBulletService_Expecter) CreateBullet(ctx any, input any) *MockBulletService_CreateBullet_Call {
	return &MockBulletService_CreateBullet_Call{Call: _e.mock.On("CreateBullet", ctx, input)}
}

func (_c *MockBulletService_CreateBullet_Call) Run(run func(ctx context.Context, input port.CreateBulletInput)) *MockBulletService_CreateBullet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.CreateBulletInput
		if args[1] != nil {
			arg1 = args[1].(port.CreateBulletInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBulletService_CreateBullet_Call) Return(bullet *entity.Bullet, err error) *MockBulletService_CreateBullet_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletService_CreateBullet_Call) RunAndReturn(run func(ctx context.Context, input port.CreateBulletInput) (*entity.Bullet, error)) *MockBulletService_CreateBullet_Call {
	_c.Call.Return(run)
	return _c
}

// ListBullets provides a mock function for the type MockBulletService
func (_mock *MockBulletService) ListBullets(ctx context.Context, userID uuid.UUID) ([]*entity.Bullet, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListBullets")
	}

	var r0 []*entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Bullet, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Bullet); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_ListBullets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBullets'
type MockBulletService_ListBullets_Call struct {
	*mock.Call
}

// ListBullets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBulletService_Expecter) ListBullets(ctx any, userID any) *MockBulletService_ListBullets_Call {
	return &MockBulletService_ListBullets_Call{Call: _e.mock.On("ListBullets", ctx, userID)}
}

func (_c *MockBulletService_ListBullets_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBulletService_ListBullets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBulletService_ListBullets_Call) Return(bullets []*entity.Bullet, err error) *MockBulletService_ListBullets_Call {
	_c.Call.Return(bullets, err)
	return _c
}

func (_c *MockBulletService_ListBullets_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.Bullet, error)) *MockBulletService_ListBullets_Call {
	_c.Call.Return(run)
	return _c
}

// MigrateBullet provides a mock function for the type MockBulletService
func (_mock *MockBulletService) MigrateBullet(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MigrateBullet")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Bullet, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Bullet); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_MigrateBullet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateBullet'
type MockBulletService_MigrateBullet_Call struct {
	*mock.Call
}

// MigrateBullet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockBulletService_Expecter) MigrateBullet(ctx any, id any, userID any) *MockBulletService_MigrateBullet_Call {
	return &MockBulletService_MigrateBullet_Call{Call: _e.mock.On("MigrateBullet", ctx, id, userID)}
}

func (_c *MockBulletService_MigrateBullet_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockBulletService_MigrateBullet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBulletService_MigrateBullet_Call) Return(bullet *entity.Bullet, err error) *MockBulletService_MigrateBullet_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletService_MigrateBullet_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error)) *MockBulletService_MigrateBullet_Call {
	_c.Call.Return(run)
	return _c
}
