// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alexnesterov/rapidlog-api/internal/domain/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBulletRepository creates a new instance of MockBulletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBulletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBulletRepository {
	mock := &MockBulletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBulletRepository is an autogenerated mock type for the BulletRepository type
type MockBulletRepository struct {
	mock.Mock
}

type MockBulletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBulletRepository) EXPECT() *MockBulletRepository_Expecter {
	return &MockBulletRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) Create(ctx context.Context, bullet *entity.Bullet) error {
	ret := _mock.Called(ctx, bullet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Bullet) error); ok {
		r0 = returnFunc(ctx, bullet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBulletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBulletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - bullet *entity.Bullet
func (_e *MockBulletRepository_Expecter) Create(ctx any, bullet any) *MockBulletRepository_Create_Call {
	return &MockBulletRepository_Create_Call{Call: _e.mock.On("Create", ctx, bullet)}
}

func (_c *MockBulletRepository_Create_Call) Run(run func(ctx context.Context, bullet *entity.Bullet)) *MockBulletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Bullet
		if args[1] != nil {
			arg1 = args[1].(*entity.Bullet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBulletRepository_Create_Call) Return(err error) *MockBulletRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBulletRepository_Create_Call) RunAndReturn(run func(ctx context.Context, bullet *entity.Bullet) error) *MockBulletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) Get(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Bullet, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Bullet); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBulletRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockBulletRepository_Expecter) Get(ctx any, id any, userID any) *MockBulletRepository_Get_Call {
	return &MockBulletRepository_Get_Call{Call: _e.mock.On("Get", ctx, id, userID)}
}

func (_c *MockBulletRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockBulletRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBulletRepository_Get_Call) Return(bullet *entity.Bullet, err error) *MockBulletRepository_Get_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Bullet, error)) *MockBulletRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) List(ctx context.Context, userID uuid.UUID) ([]*entity.Bullet, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Bullet, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Bullet); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBulletRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBulletRepository_Expecter) List(ctx any, userID any) *MockBulletRepository_List_Call {
	return &MockBulletRepository_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockBulletRepository_List_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBulletRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBulletRepository_List_Call) Return(bullets []*entity.Bullet, err error) *MockBulletRepository_List_Call {
	_c.Call.Return(bullets, err)
	return _c
}

func (_c *MockBulletRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.Bullet, error)) *MockBulletRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBulletRepository
func (_mock *MockBulletRepository) Update(ctx context.Context, bullet *entity.Bullet) error {
	ret := _mock.Called(ctx, bullet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Bullet) error); ok {
		r0 = returnFunc(ctx, bullet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBulletRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBulletRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - bullet *entity.Bullet
func (_e *MockBulletRepository_Expecter) Update(ctx any, bullet any) *MockBulletRepository_Update_Call {
	return &MockBulletRepository_Update_Call{Call: _e.mock.On("Update", ctx, bullet)}
}

func (_c *MockBulletRepository_Update_Call) Run(run func(ctx context.Context, bullet *entity.Bullet)) *MockBulletRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Bullet
		if args[1] != nil {
			arg1 = args[1].(*entity.Bullet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBulletRepository_Update_Call) Return(err error) *MockBulletRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBulletRepository_Update_Call) RunAndReturn(run func(ctx context.Context, bullet *entity.Bullet) error) *MockBulletRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
