// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alexnesterov/rapidlog-api/internal/domain/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollectionRepository creates a new instance of MockCollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionRepository {
	mock := &MockCollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectionRepository is an autogenerated mock type for the CollectionRepository type
type MockCollectionRepository struct {
	mock.Mock
}

type MockCollectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionRepository) EXPECT() *MockCollectionRepository_Expecter {
	return &MockCollectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) Create(collection *entity.Collection) error {
	ret := _mock.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Collection) error); ok {
		r0 = returnFunc(collection)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCollectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - collection *entity.Collection
func (_e *MockCollectionRepository_Expecter) Create(collection any) *MockCollectionRepository_Create_Call {
	return &MockCollectionRepository_Create_Call{Call: _e.mock.On("Create", collection)}
}

func (_c *MockCollectionRepository_Create_Call) Run(run func(collection *entity.Collection)) *MockCollectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Collection
		if args[0] != nil {
			arg0 = args[0].(*entity.Collection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_Create_Call) Return(err error) *MockCollectionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectionRepository_Create_Call) RunAndReturn(run func(collection *entity.Collection) error) *MockCollectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) Delete(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCollectionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCollectionRepository_Expecter) Delete(id any) *MockCollectionRepository_Delete_Call {
	return &MockCollectionRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCollectionRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockCollectionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_Delete_Call) Return(err error) *MockCollectionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectionRepository_Delete_Call) RunAndReturn(run func(id uuid.UUID) error) *MockCollectionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) List() ([]*entity.Collection, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Collection, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Collection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCollectionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockCollectionRepository_Expecter) List() *MockCollectionRepository_List_Call {
	return &MockCollectionRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockCollectionRepository_List_Call) Run(run func()) *MockCollectionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectionRepository_List_Call) Return(collections []*entity.Collection, err error) *MockCollectionRepository_List_Call {
	_c.Call.Return(collections, err)
	return _c
}

func (_c *MockCollectionRepository_List_Call) RunAndReturn(run func() ([]*entity.Collection, error)) *MockCollectionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) Read(id uuid.UUID) (*entity.Collection, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entity.Collection, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entity.Collection); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockCollectionRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCollectionRepository_Expecter) Read(id any) *MockCollectionRepository_Read_Call {
	return &MockCollectionRepository_Read_Call{Call: _e.mock.On("Read", id)}
}

func (_c *MockCollectionRepository_Read_Call) Run(run func(id uuid.UUID)) *MockCollectionRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_Read_Call) Return(collection *entity.Collection, err error) *MockCollectionRepository_Read_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockCollectionRepository_Read_Call) RunAndReturn(run func(id uuid.UUID) (*entity.Collection, error)) *MockCollectionRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) Update(collection *entity.Collection) error {
	ret := _mock.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Collection) error); ok {
		r0 = returnFunc(collection)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCollectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - collection *entity.Collection
func (_e *MockCollectionRepository_Expecter) Update(collection any) *MockCollectionRepository_Update_Call {
	return &MockCollectionRepository_Update_Call{Call: _e.mock.On("Update", collection)}
}

func (_c *MockCollectionRepository_Update_Call) Run(run func(collection *entity.Collection)) *MockCollectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Collection
		if args[0] != nil {
			arg0 = args[0].(*entity.Collection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_Update_Call) Return(err error) *MockCollectionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectionRepository_Update_Call) RunAndReturn(run func(collection *entity.Collection) error) *MockCollectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
