// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alexnesterov/rapidlog-api/internal/domain/entity"
	"github.com/alexnesterov/rapidlog-api/internal/domain/port"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollectionService creates a new instance of MockCollectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionService {
	mock := &MockCollectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectionService is an autogenerated mock type for the CollectionService type
type MockCollectionService struct {
	mock.Mock
}

type MockCollectionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionService) EXPECT() *MockCollectionService_Expecter {
	return &MockCollectionService_Expecter{mock: &_m.Mock}
}

// CreateCollection provides a mock function for the type MockCollectionService
func (_mock *MockCollectionService) CreateCollection(req port.CreateCollectionRequest) (*entity.Collection, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(port.CreateCollectionRequest) (*entity.Collection, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(port.CreateCollectionRequest) *entity.Collection); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(port.CreateCollectionRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionService_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type MockCollectionService_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - req port.CreateCollectionRequest
func (_e *MockCollectionService_Expecter) CreateCollection(req any) *MockCollectionService_CreateCollection_Call {
	return &MockCollectionService_CreateCollection_Call{Call: _e.mock.On("CreateCollection", req)}
}

func (_c *MockCollectionService_CreateCollection_Call) Run(run func(req port.CreateCollectionRequest)) *MockCollectionService_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 port.CreateCollectionRequest
		if args[0] != nil {
			arg0 = args[0].(port.CreateCollectionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionService_CreateCollection_Call) Return(collection *entity.Collection, err error) *MockCollectionService_CreateCollection_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockCollectionService_CreateCollection_Call) RunAndReturn(run func(req port.CreateCollectionRequest) (*entity.Collection, error)) *MockCollectionService_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type MockCollectionService
func (_mock *MockCollectionService) DeleteCollection(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectionService_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockCollectionService_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCollectionService_Expecter) DeleteCollection(id any) *MockCollectionService_DeleteCollection_Call {
	return &MockCollectionService_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", id)}
}

func (_c *MockCollectionService_DeleteCollection_Call) Run(run func(id uuid.UUID)) *MockCollectionService_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionService_DeleteCollection_Call) Return(err error) *MockCollectionService_DeleteCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectionService_DeleteCollection_Call) RunAndReturn(run func(id uuid.UUID) error) *MockCollectionService_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockCollectionService
func (_mock *MockCollectionService) ListCollections() ([]*entity.Collection, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 []*entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Collection, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Collection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionService_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockCollectionService_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
func (_e *MockCollectionService_Expecter) ListCollections() *MockCollectionService_ListCollections_Call {
	return &MockCollectionService_ListCollections_Call{Call: _e.mock.On("ListCollections")}
}

func (_c *MockCollectionService_ListCollections_Call) Run(run func()) *MockCollectionService_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectionService_ListCollections_Call) Return(collections []*entity.Collection, err error) *MockCollectionService_ListCollections_Call {
	_c.Call.Return(collections, err)
	return _c
}

func (_c *MockCollectionService_ListCollections_Call) RunAndReturn(run func() ([]*entity.Collection, error)) *MockCollectionService_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}

// ReadCollection provides a mock function for the type MockCollectionService
func (_mock *MockCollectionService) ReadCollection(id uuid.UUID) (*entity.Collection, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ReadCollection")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entity.Collection, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entity.Collection); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionService_ReadCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCollection'
type MockCollectionService_ReadCollection_Call struct {
	*mock.Call
}

// ReadCollection is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCollectionService_Expecter) ReadCollection(id any) *MockCollectionService_ReadCollection_Call {
	return &MockCollectionService_ReadCollection_Call{Call: _e.mock.On("ReadCollection", id)}
}

func (_c *MockCollectionService_ReadCollection_Call) Run(run func(id uuid.UUID)) *MockCollectionService_ReadCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionService_ReadCollection_Call) Return(collection *entity.Collection, err error) *MockCollectionService_ReadCollection_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockCollectionService_ReadCollection_Call) RunAndReturn(run func(id uuid.UUID) (*entity.Collection, error)) *MockCollectionService_ReadCollection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCollection provides a mock function for the type MockCollectionService
func (_mock *MockCollectionService) UpdateCollection(req port.UpdateCollectionRequest) (*entity.Collection, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCollection")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(port.UpdateCollectionRequest) (*entity.Collection, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(port.UpdateCollectionRequest) *entity.Collection); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(port.UpdateCollectionRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionService_UpdateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCollection'
type MockCollectionService_UpdateCollection_Call struct {
	*mock.Call
}

// UpdateCollection is a helper method to define mock.On call
//   - req port.UpdateCollectionRequest
func (_e *MockCollectionService_Expecter) UpdateCollection(req any) *MockCollectionService_UpdateCollection_Call {
	return &MockCollectionService_UpdateCollection_Call{Call: _e.mock.On("UpdateCollection", req)}
}

func (_c *MockCollectionService_UpdateCollection_Call) Run(run func(req port.UpdateCollectionRequest)) *MockCollectionService_UpdateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 port.UpdateCollectionRequest
		if args[0] != nil {
			arg0 = args[0].(port.UpdateCollectionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectionService_UpdateCollection_Call) Return(collection *entity.Collection, err error) *MockCollectionService_UpdateCollection_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockCollectionService_UpdateCollection_Call) RunAndReturn(run func(req port.UpdateCollectionRequest) (*entity.Collection, error)) *MockCollectionService_UpdateCollection_Call {
	_c.Call.Return(run)
	return _c
}
