// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alexnesterov/rapidlog-api/internal/domain/entity"
	"github.com/alexnesterov/rapidlog-api/internal/domain/port"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBulletService creates a new instance of MockBulletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBulletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBulletService {
	mock := &MockBulletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBulletService is an autogenerated mock type for the BulletService type
type MockBulletService struct {
	mock.Mock
}

type MockBulletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBulletService) EXPECT() *MockBulletService_Expecter {
	return &MockBulletService_Expecter{mock: &_m.Mock}
}

// CompleteBullet provides a mock function for the type MockBulletService
func (_mock *MockBulletService) CompleteBullet(id uuid.UUID) (*entity.Bullet, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteBullet")
	}

	var r0 *entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entity.Bullet, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entity.Bullet); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_CompleteBullet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteBullet'
type MockBulletService_CompleteBullet_Call struct {
	*mock.Call
}

// CompleteBullet is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBulletService_Expecter) CompleteBullet(id any) *MockBulletService_CompleteBullet_Call {
	return &MockBulletService_CompleteBullet_Call{Call: _e.mock.On("CompleteBullet", id)}
}

func (_c *MockBulletService_CompleteBullet_Call) Run(run func(id uuid.UUID)) *MockBulletService_CompleteBullet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBulletService_CompleteBullet_Call) Return(bullet *entity.Bullet, err error) *MockBulletService_CompleteBullet_Call {
	_c.Call.Return(bullet, err)
	return _c
}

func (_c *MockBulletService_CompleteBullet_Call) RunAndReturn(run func(id uuid.UUID) (*entity.Bullet, error)) *MockBulletService_CompleteBullet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBullet provides a mock function for the type MockBulletService
func (_mock *MockBulletService) CreateBullet(input port.CreateBulletInput) (port.CreateBulletOutput, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBullet")
	}

	var r0 port.CreateBulletOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(port.CreateBulletInput) (port.CreateBulletOutput, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(port.CreateBulletInput) port.CreateBulletOutput); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Get(0).(port.CreateBulletOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(port.CreateBulletInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_CreateBullet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBullet'
type MockBulletService_CreateBullet_Call struct {
	*mock.Call
}

// CreateBullet is a helper method to define mock.On call
//   - input port.CreateBulletInput
func (_e *MockBulletService_Expecter) CreateBullet(input any) *MockBulletService_CreateBullet_Call {
	return &MockBulletService_CreateBullet_Call{Call: _e.mock.On("CreateBullet", input)}
}

func (_c *MockBulletService_CreateBullet_Call) Run(run func(input port.CreateBulletInput)) *MockBulletService_CreateBullet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 port.CreateBulletInput
		if args[0] != nil {
			arg0 = args[0].(port.CreateBulletInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBulletService_CreateBullet_Call) Return(createBulletOutput port.CreateBulletOutput, err error) *MockBulletService_CreateBullet_Call {
	_c.Call.Return(createBulletOutput, err)
	return _c
}

func (_c *MockBulletService_CreateBullet_Call) RunAndReturn(run func(input port.CreateBulletInput) (port.CreateBulletOutput, error)) *MockBulletService_CreateBullet_Call {
	_c.Call.Return(run)
	return _c
}

// ListBullets provides a mock function for the type MockBulletService
func (_mock *MockBulletService) ListBullets() ([]*entity.Bullet, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBullets")
	}

	var r0 []*entity.Bullet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Bullet, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Bullet); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Bullet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBulletService_ListBullets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBullets'
type MockBulletService_ListBullets_Call struct {
	*mock.Call
}

// ListBullets is a helper method to define mock.On call
func (_e *MockBulletService_Expecter) ListBullets() *MockBulletService_ListBullets_Call {
	return &MockBulletService_ListBullets_Call{Call: _e.mock.On("ListBullets")}
}

func (_c *MockBulletService_ListBullets_Call) Run(run func()) *MockBulletService_ListBullets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBulletService_ListBullets_Call) Return(bullets []*entity.Bullet, err error) *MockBulletService_ListBullets_Call {
	_c.Call.Return(bullets, err)
	return _c
}

func (_c *MockBulletService_ListBullets_Call) RunAndReturn(run func() ([]*entity.Bullet, error)) *MockBulletService_ListBullets_Call {
	_c.Call.Return(run)
	return _c
}
