// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdentityService creates a new instance of MockIdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIdentityService is an autogenerated mock type for the IdentityService type
type MockIdentityService struct {
	mock.Mock
}

type MockIdentityService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityService) EXPECT() *MockIdentityService_Expecter {
	return &MockIdentityService_Expecter{mock: &_m.Mock}
}

// ResolveSession provides a mock function for the type MockIdentityService
func (_mock *MockIdentityService) ResolveSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResolveSession")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityService_ResolveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveSession'
type MockIdentityService_ResolveSession_Call struct {
	*mock.Call
}

// ResolveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIdentityService_Expecter) ResolveSession(ctx any, id any) *MockIdentityService_ResolveSession_Call {
	return &MockIdentityService_ResolveSession_Call{Call: _e.mock.On("ResolveSession", ctx, id)}
}

func (_c *MockIdentityService_ResolveSession_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIdentityService_ResolveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityService_ResolveSession_Call) Return(uUID uuid.UUID, err error) *MockIdentityService_ResolveSession_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockIdentityService_ResolveSession_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (uuid.UUID, error)) *MockIdentityService_ResolveSession_Call {
	_c.Call.Return(run)
	return _c
}
